### ISSUE TITLE
how do i set it up?

### ISSUE THREAD

**Issue by soapy75** [RandomLemon10/Google-Classroom-Spam-bot#1]

**Comment by TheLickIn13Keys** [comment]
Sorry for the late reply. Simply head on over to the releases (https://github.com/TheLickIn13Keys/Google-Classroom-Spam-bot/releases/tag/1.0.0) and click the .vbs file and run it on your computer, it will guide you through setup.

**Comment by soapy75** [comment]
thx

**Comment by soapy75** [comment]
thx
